# Training settings
training:
  epochs: 90
  batch_size: 256
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 5
  model_save_path: "checkpoints/best_model.pth"
  pin_memory: true
  prefetch_factor: 2

# Data settings
data:
  data_path: "/data/ILSVRC/ILSVRC/Data/CLS-LOC"  # Updated path
  num_workers: 8
  input_size: 224
  num_classes: 1000
  train_samples: 1281167
  val_samples: 50000
  train_path: "train"
  val_path: "val"

# Model settings
model:
  architecture: "resnet50"
  pretrained: false

# Augmentation settings
augmentation:
  random_crop: true
  random_horizontal_flip: true
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Logging settings
logging:
  project_name: "imagenet-resnet50"
  log_interval: 100
  wandb_enabled: false
  run_name: "baseline"

# Hardware settings
hardware:
  device: "cuda"
  multi_gpu: false